### ISSUE TITLE
Message Board

### ISSUE THREAD

**Issue by Winton1996** [SUisnotMe/SUisnotMe.github.io#2]
How about setting up a message board to allow more neutral opinions exposed?
# against the bias opinions from ustSU
# correct the rumors from ustSU
# make our voice heard
# SU is not me

**Comment by SUisnotMe** [comment]
Thank you for your advise. We will make this happen as long as we have time.

**Comment by SUisnotMe** [comment]
We have used a comment API from intensedebate. Hope we can find you in the comments.
